name: Download-Rancher-Desktop

on:
  push: {}
  pull_request: {}

jobs :
  download_unzip_rancher_desktop:
    runs-on: macos-11.15
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm ci
    - run: npm run downloadrancher


